export const COLORS = [
  'black',
  'black & white / tuxedo',
  'blue-gray',
  'blue',
  'calico',
  'chocolate',
  'cinnamon',
  'cream',
  'fawn',
  'gray',
  'gray & white',
  'lilac',
  'orange',
  'orange & white',
  'red',
  'smoke',
  'tabby',
  'tortoiseshell (gray)',
  'tortoiseshell (brown)',
  'tuxedo',
  'white',
];

export const BREEDS = [
  'abyssinian',
  'american bobtail',
  'american curl',
  'american shorthair',
  'american wirehair',
  'balinese',
  'bengal',
  'birman',
  'bombay',
  'british shorthair',
  'burmese',
  'chartreux',
  'chausie',
  'cornish rex',
  'devon rex',
  'donskoy',
  'egyptian mau',
  'exotic shorthair',
  'havana',
  'highlander',
  'himalayan',
  'household pet cat',
  'household pet kitten',
  'japanese bobtail',
  'korat',
  'kurilian bobtail',
  'laperm',
  'maine coon',
  'manx',
  'minskin',
  'munchkin',
  'nebelung',
  'norwegian forest cat',
  'ocicat',
  'ojos azules',
  'oriental',
  'persian',
  'peterbald',
  'pixiebob',
  'ragdoll',
  'russian blue',
  'savannah',
  'scottish fold',
  'selkirk rex',
  'serengeti',
  'siberian',
  'siamese',
  'singapura',
  'snowshoe',
  'sokoke',
  'somali',
  'sphynx',
  'thai',
  'tonkinese',
  'toyger',
  'turkish angora',
  'turkish van',
];

export const COAT_LENGTHS = ['hairless', 'short', 'medium', 'long'];
