import { PetDetails, PetSpecies } from '@rufferal/store';
import * as yup from 'yup';
import { FieldOption } from '././../../../atoms';

/****************** FORM ******************/
export const optionSchema: (
  requiredMessage: string
) => yup.ObjectSchema<FieldOption> = (requiredMessage: string) => {
  return yup.object({
    id: yup.string().required(),
    label: yup.string().required(),
    value: yup.string().required(requiredMessage),
  });
};
export const petDetailsSchema: (
  species: PetSpecies
) => yup.ObjectSchema<PetDetails> = (species: PetSpecies) =>
  yup
    .object({
      species: yup
        .string()
        .oneOf(['cat', 'dog'])
        .required(`Missing species: ${species} type declaration`),
      name: yup.string().required(`Please provide a name for your ${species}`),
      color: optionSchema(`Please provide your ${species}'s color`),
      breed: optionSchema(`Please provide your ${species}'s breed`),
      sex: optionSchema(`Please provide your ${species}'s sex`),
      age: optionSchema(`Please provide your ${species}'s age`),
      size: optionSchema(`Please provide your ${species}'s size`),
      status: optionSchema(`Please provide your ${species}'s status`),
    })
    .required();

/****************** SHARED ******************/
export const SEX = ['male', 'female'];
export const SEX_OPTIONS = [
  {
    id: 'whseq6w1c1e',
    label: 'Male',
    value: 'male',
  },
  {
    id: 'axhqeqqr8lt',
    label: 'Female',
    value: 'female',
  },
];

export const STATUS = ['yes', 'no'];
export const STATUS_OPTIONS = [
  {
    id: '6az7qovb505',
    label: 'Yes',
    value: 'yes',
  },
  {
    id: 'xmx7j5xkcxj',
    label: 'No',
    value: 'no',
  },
];

/****************** CATS ******************/
export const CAT_COLORS = [
  'black',
  'black & white',
  'blue-gray',
  'blue',
  'calico',
  'chocolate',
  'cinnamon',
  'cream',
  'fawn',
  'gray',
  'gray & white',
  'lilac',
  'orange',
  'orange & white',
  'red',
  'smoke',
  'tabby',
  'tortoiseshell (gray)',
  'tortoiseshell (brown)',
  'tuxedo',
  'white',
];
export const CAT_COLOR_OPTIONS = [
  {
    id: 'hwfkdiwxkph',
    label: 'Black',
    value: 'black',
  },
  {
    id: 'kbiac12lmi',
    label: 'Black & White',
    value: 'black & white',
  },
  {
    id: '1a0p1pmf7u9',
    label: 'Blue-Gray',
    value: 'blue-gray',
  },
  {
    id: 'fiwsd9xdnj',
    label: 'Blue',
    value: 'blue',
  },
  {
    id: '3yfjhqp0idu',
    label: 'Calico',
    value: 'calico',
  },
  {
    id: 'yvvmnta9nbl',
    label: 'Chocolate',
    value: 'chocolate',
  },
  {
    id: 'x2tjguiskq',
    label: 'Cinnamon',
    value: 'cinnamon',
  },
  {
    id: 'bhk55w898l8',
    label: 'Cream',
    value: 'cream',
  },
  {
    id: 'qw6xu7s64tr',
    label: 'Fawn',
    value: 'fawn',
  },
  {
    id: 'iandunp647',
    label: 'Gray',
    value: 'gray',
  },
  {
    id: '3kqy0unqj9',
    label: 'Gray & White',
    value: 'gray & white',
  },
  {
    id: 'lnwrtggwlw',
    label: 'Lilac',
    value: 'lilac',
  },
  {
    id: 'lgqgr0rsw9',
    label: 'Orange',
    value: 'orange',
  },
  {
    id: 'yh5cm5rxg6d',
    label: 'Orange & White',
    value: 'orange & white',
  },
  {
    id: '0tckzdba8o',
    label: 'Red',
    value: 'red',
  },
  {
    id: '1don7x7af15',
    label: 'Smoke',
    value: 'smoke',
  },
  {
    id: 'yc37tjt9am7',
    label: 'Tabby',
    value: 'tabby',
  },
  {
    id: 'ykyxexdb62g',
    label: 'Tortoiseshell (Gray)',
    value: 'tortoiseshell (gray)',
  },
  {
    id: 'mpjncspg09',
    label: 'Tortoiseshell (Brown)',
    value: 'tortoiseshell (brown)',
  },
  {
    id: 'xd62izkn27g',
    label: 'Tuxedo',
    value: 'tuxedo',
  },
  {
    id: 'stsp2t9h59',
    label: 'White',
    value: 'white',
  },
];

export const CAT_BREEDS = [
  'abyssinian',
  'american bobtail',
  'american curl',
  'american shorthair',
  'american wirehair',
  'balinese',
  'bengal',
  'birman',
  'bombay',
  'british shorthair',
  'burmese',
  'chartreux',
  'chausie',
  'cornish rex',
  'devon ex',
  'donskoy',
  'egyptian mau',
  'exotic shorthair',
  'havana',
  'highlander',
  'himalayan',
  'household pet cat',
  'household pet kitten',
  'japanese bobtail',
  'korat',
  'kurilian bobtail',
  'laperm',
  'maine coon',
  'manx',
  'minskin',
  'munchkin',
  'nebelung',
  'norwegian forest cat',
  'ocicat',
  'ojos azules',
  'oriental',
  'persian',
  'peterbald',
  'pixiebob',
  'ragdoll',
  'russian blue',
  'savannah',
  'scottish fold',
  'selkirk rex',
  'serengeti',
  'siamese',
  'siberian',
  'singapura',
  'snowshoe',
  'sokoke',
  'somali',
  'sphynx',
  'thai',
  'tonkinese',
  'toyger',
  'turkish angora',
  'turkish van',
];
export const CAT_BREED_OPTIONS = [
  {
    id: 'r7x00i47j3',
    label: 'Abyssinian',
    value: 'abyssinian',
  },
  {
    id: 'n8y1rmdw9lb',
    label: 'American Bobtail',
    value: 'american bobtail',
  },
  {
    id: 'rnjv5gjwth',
    label: 'American Curl',
    value: 'american curl',
  },
  {
    id: 'raj54eu40jk',
    label: 'American Shorthair',
    value: 'american shorthair',
  },
  {
    id: 'na9z9ec3i99',
    label: 'American Wirehair',
    value: 'american wirehair',
  },
  {
    id: 'q7z80hfegq8',
    label: 'Balinese',
    value: 'balinese',
  },
  {
    id: 'vohwanmurt',
    label: 'Bengal',
    value: 'bengal',
  },
  {
    id: 'ggsg4u4yiwq',
    label: 'Birman',
    value: 'birman',
  },
  {
    id: 'xoxpvpaezt8',
    label: 'Bombay',
    value: 'bombay',
  },
  {
    id: 'esgh3k12kgh',
    label: 'British Shorthair',
    value: 'british shorthair',
  },
  {
    id: 'r0sjtbfv42',
    label: 'Burmese',
    value: 'burmese',
  },
  {
    id: 'iph4vfwjfy',
    label: 'Chartreux',
    value: 'chartreux',
  },
  {
    id: '3dd99sq551y',
    label: 'Chausie',
    value: 'chausie',
  },
  {
    id: 'j0o7f72bbw',
    label: 'Cornish Rex',
    value: 'cornish rex',
  },
  {
    id: 'x4vryt43fjo',
    label: 'Devon Ex',
    value: 'devon ex',
  },
  {
    id: 'tzdribhelrc',
    label: 'Donskoy',
    value: 'donskoy',
  },
  {
    id: 'a3kfj5546w',
    label: 'Egyptian Mau',
    value: 'egyptian mau',
  },
  {
    id: 'wpka68xkb6',
    label: 'Exotic Shorthair',
    value: 'exotic shorthair',
  },
  {
    id: 't82hwy1jo8o',
    label: 'Havana',
    value: 'havana',
  },
  {
    id: '88x8n7guzl4',
    label: 'Highlander',
    value: 'highlander',
  },
  {
    id: 'znhsiyxl6r',
    label: 'Himalayan',
    value: 'himalayan',
  },
  {
    id: 'mh0e0uj9o0n',
    label: 'Household Pet Cat',
    value: 'household pet cat',
  },
  {
    id: 'xx6iy7xb7p',
    label: 'Household Pet Kitten',
    value: 'household pet kitten',
  },
  {
    id: 'uckolb1pql',
    label: 'Japanese Bobtail',
    value: 'japanese bobtail',
  },
  {
    id: 'pzqv4p3twy',
    label: 'Korat',
    value: 'korat',
  },
  {
    id: 'p9j7nw2bsos',
    label: 'Kurilian Bobtail',
    value: 'kurilian bobtail',
  },
  {
    id: '51up1tyyler',
    label: 'Laperm',
    value: 'laperm',
  },
  {
    id: '9jhdfyvqphw',
    label: 'Maine Coon',
    value: 'maine coon',
  },
  {
    id: 'wg90642rl2o',
    label: 'Manx',
    value: 'manx',
  },
  {
    id: 'ghom60pq07i',
    label: 'Minskin',
    value: 'minskin',
  },
  {
    id: 'lkpbc5kxaep',
    label: 'Munchkin',
    value: 'munchkin',
  },
  {
    id: 'p3vdhl86jap',
    label: 'Nebelung',
    value: 'nebelung',
  },
  {
    id: 'gzruwu9qr9',
    label: 'Norwegian Forest Cat',
    value: 'norwegian forest cat',
  },
  {
    id: 'ao8aqpm6x9c',
    label: 'Ocicat',
    value: 'ocicat',
  },
  {
    id: 'ayvvwvxxdem',
    label: 'Ojos Azules',
    value: 'ojos azules',
  },
  {
    id: 'cmggd4rcwx',
    label: 'Oriental',
    value: 'oriental',
  },
  {
    id: 'ovxyctom14j',
    label: 'Persian',
    value: 'persian',
  },
  {
    id: '0ls2f661hm6q',
    label: 'Peterbald',
    value: 'peterbald',
  },
  {
    id: 'iht9a3hkm1a',
    label: 'Pixiebob',
    value: 'pixiebob',
  },
  {
    id: 'pqmox49w95',
    label: 'Ragdoll',
    value: 'ragdoll',
  },
  {
    id: 'svzss8v4iwk',
    label: 'Russian Blue',
    value: 'russian blue',
  },
  {
    id: 'ym2nbwkj8qs',
    label: 'Savannah',
    value: 'savannah',
  },
  {
    id: '7inx46ptwk4',
    label: 'Scottish Fold',
    value: 'scottish fold',
  },
  {
    id: '998x7l0u49v',
    label: 'Selkirk Rex',
    value: 'selkirk rex',
  },
  {
    id: 'hoaw3wr2mqu',
    label: 'Serengeti',
    value: 'serengeti',
  },
  {
    id: 'wpsvkewfyu',
    label: 'Siamese',
    value: 'siamese',
  },
  {
    id: '5efwuawpht',
    label: 'Siberian',
    value: 'siberian',
  },
  {
    id: 'nffyrlsfpxm',
    label: 'Singapura',
    value: 'singapura',
  },
  {
    id: 'qznhvq3j1q',
    label: 'Snowshoe',
    value: 'snowshoe',
  },
  {
    id: '4ltetojf42j',
    label: 'Sokoke',
    value: 'sokoke',
  },
  {
    id: 'evv5a5uzta',
    label: 'Somali',
    value: 'somali',
  },
  {
    id: 'zl2hikdlsij',
    label: 'Sphynx',
    value: 'sphynx',
  },
  {
    id: 'nu9ee4rpikg',
    label: 'Thai',
    value: 'thai',
  },
  {
    id: 'qw35nyft5zs',
    label: 'Tonkinese',
    value: 'tonkinese',
  },
  {
    id: 'i7qvub0tbv',
    label: 'Toyger',
    value: 'toyger',
  },
  {
    id: 'gj9hdeai72',
    label: 'Turkish Angora',
    value: 'turkish angora',
  },
  {
    id: 'd3x1y51gfqm',
    label: 'Turkish Van',
    value: 'turkish van',
  },
];

export const CAT_AGES = [
  'Kitten (0–9 months)',
  'Young (9 months – 2 years)',
  'Adult (2–8 years)',
  'Senior (8+ years)',
];
export const CAT_AGE_OPTIONS = [
  {
    id: '1wqu4bnz908',
    label: 'Kitten (0–9 Months)',
    value: 'kitten (0–9 months)',
  },
  {
    id: 'nml5h80uk9l',
    label: 'Young (9 Months – 2 Years)',
    value: 'young (9 months – 2 years)',
  },
  {
    id: 'l0joaxmw6ym',
    label: 'Adult (2–8 Years)',
    value: 'adult (2–8 years)',
  },
  {
    id: '16insi42o16',
    label: 'Senior (8+ Years)',
    value: 'senior (8+ years)',
  },
];

export const CAT_SIZES = [
  'Small (0–6 lbs)',
  'Medium (7–11 lbs)',
  'Large (12–16 lbs)',
  'Extra large (16+ lbs)',
];
export const CAT_SIZE_OPTIONS = [
  {
    id: 'ffad55kke4',
    label: 'Small (0–6 Lbs)',
    value: 'small (0–6 lbs)',
  },
  {
    id: 'ynxe968m0d',
    label: 'Medium (7–11 Lbs)',
    value: 'medium (7–11 lbs)',
  },
  {
    id: 'k8ycy6rq9x',
    label: 'Large (12–16 Lbs)',
    value: 'large (12–16 lbs)',
  },
  {
    id: '9sh09lezp4k',
    label: 'Extra Large (16+ Lbs)',
    value: 'extra large (16+ lbs)',
  },
];

/****************** DOGS ******************/
export const DOG_COLORS = [
  'apricot / beige',
  'black & brown',
  'black & white',
  'black',
  'blue-gray',
  'blue',
  'brown & white',
  'brown',
  'chocolate',
  'cinnamon',
  'cream',
  'fawn',
  'golden / tan',
  'golden',
  'gray / blue / silver',
  'gray',
  'merle (blue)',
  'merle (red)',
  'orange',
  'red / chestnut / orange',
  'red',
  'silver',
  'smoke',
  'white / cream',
  'white',
  'yellow',
];
export const DOG_COLOR_OPTIONS = [
  {
    id: 'kkfjicu8ab',
    label: 'Apricot / Beige',
    value: 'apricot / beige',
  },
  {
    id: '74kgz8267nt',
    label: 'Black & Brown',
    value: 'black & brown',
  },
  {
    id: 'anubuuzef3u',
    label: 'Black & White',
    value: 'black & white',
  },
  {
    id: 'pjn2mic69ti',
    label: 'Black',
    value: 'black',
  },
  {
    id: '0rc25hnv9m7p',
    label: 'Blue-gray',
    value: 'blue-gray',
  },
  {
    id: 'alei3qpsn4u',
    label: 'Blue',
    value: 'blue',
  },
  {
    id: 'sbfdmqdt95',
    label: 'Brown & White',
    value: 'brown & white',
  },
  {
    id: 'txkvsp8a0w',
    label: 'Brown',
    value: 'brown',
  },
  {
    id: 'x77i245cz5c',
    label: 'Chocolate',
    value: 'chocolate',
  },
  {
    id: 'wszo1uodaik',
    label: 'Cinnamon',
    value: 'cinnamon',
  },
  {
    id: 'a7b3rkqld9q',
    label: 'Cream',
    value: 'cream',
  },
  {
    id: '9l2idlps3ea',
    label: 'Fawn',
    value: 'fawn',
  },
  {
    id: 'ry5d2og5nrp',
    label: 'Golden / Tan',
    value: 'golden / tan',
  },
  {
    id: 'm49m5fugji',
    label: 'Golden',
    value: 'golden',
  },
  {
    id: 'mobimtlntvk',
    label: 'Gray / Blue / Silver',
    value: 'gray / blue / silver',
  },
  {
    id: 'xqehw4aw4l',
    label: 'Gray',
    value: 'gray',
  },
  {
    id: '9xedfdim4cs',
    label: 'Merle (blue)',
    value: 'merle (blue)',
  },
  {
    id: '5h6mxx03njb',
    label: 'Merle (red)',
    value: 'merle (red)',
  },
  {
    id: '8dwudvnq1cx',
    label: 'Orange',
    value: 'orange',
  },
  {
    id: 'qt5zxtnn9uc',
    label: 'Red / Chestnut / Orange',
    value: 'red / chestnut / orange',
  },
  {
    id: 'bh6g4dr3uqf',
    label: 'Red',
    value: 'red',
  },
  {
    id: 'gnafbgoqlz9',
    label: 'Silver',
    value: 'silver',
  },
  {
    id: 'szd8i3qlg2',
    label: 'Smoke',
    value: 'smoke',
  },
  {
    id: 'ycr3gf07k2',
    label: 'White / Cream',
    value: 'white / cream',
  },
  {
    id: 'c34gbikcu6u',
    label: 'White',
    value: 'white',
  },
  {
    id: 'yhe78wx1rd',
    label: 'Yellow',
    value: 'yellow',
  },
];

export const DOG_BREEDS = [
  'affenpinscher',
  'afghan hound',
  'airedale terrier',
  'akita',
  'alaskan husky',
  'alaskan malamute',
  'alpine dachsbracke',
  'american akita',
  'american cocker spaniel',
  'american foxhound',
  'american staffordshire terrier',
  'american water spaniel',
  'appenzell cattle dog',
  'ariege pointing dog',
  'ariegeois',
  'artois hound',
  'atlas mountain dog (aidi)',
  'aussiedoodle',
  'australian cattle dog',
  'australian kelpie',
  'australian shepherd',
  'australian silky terrier',
  'australian stumpy tail cattle dog',
  'australian terrier',
  'austrian  pinscher',
  'austrian black and tan hound',
  'auvergne pointer',
  'azawakh',
  'basenji',
  'basset fauve de bretagne',
  'basset hound',
  'bavarian mountain scent hound',
  'beagle harrier',
  'beagle',
  'bearded collie',
  'beauce sheepdog',
  'bedlington terrier',
  'belgian shepherd dog',
  'bergamasco shepherd dog',
  'bernese mountain dog',
  'bichon frise',
  'billy',
  'black and tan coonhound',
  'bloodhound',
  'blue gascony basset',
  'blue gascony griffon',
  'blue heeler',
  'blue picardy spaniel',
  'bluetick coonhound',
  'bohemian shepherd dog',
  'bohemian wire-haired pointing griffon',
  'bolognese',
  'border collie',
  'border terrier',
  'borzoi - russian hunting sighthound',
  'bosnian and herzegovinian - croatian shepherd dog',
  'bosnian broken-haired hound - called barak',
  'boston terrier',
  'bourbonnais pointing dog',
  'bouvier des ardennes',
  'bouvier des flandres',
  'boxer',
  'brazilian terrier',
  'brazilian tracker',
  'briard',
  'briquet griffon vendeen',
  'brittany spaniel',
  'broholmer',
  'bull terrier',
  'bulldog',
  'bullmastiff',
  'burgos pointing dog',
  'cairn terrier',
  'canaan dog',
  'canadian eskimo dog',
  'canarian warren hound',
  'castro laboreiro dog',
  'catalan sheepdog',
  'caucasian shepherd dog',
  'cavalier king charles spaniel',
  'central asia shepherd dog',
  'cesky terrier',
  'chesapeake bay retriever',
  'chihuahua',
  'chinese crested dog',
  'chow chow',
  'cimarrón uruguayo',
  'clumber spaniel',
  'coarse-haired styrian hound',
  'collie rough',
  'collie smooth',
  'continental bulldog',
  'continental toy spaniel',
  'coton de tulear',
  'croatian shepherd dog',
  'curly coated retriever',
  'czechoslovakian wolfdog',
  'dachshund',
  'dalmatian',
  'dandie dinmont terrier',
  'danish-swedish farmdog',
  'deerhound',
  'deutsch langhaar',
  'deutsch stichelhaar',
  'dobermann',
  'dogo argentino',
  'dogue de bordeaux',
  'drentsche partridge dog',
  'drever',
  'dutch schapendoes',
  'dutch shepherd dog',
  'dutch smoushond',
  'east siberian laika',
  'english cocker spaniel',
  'english foxhound',
  'english pointer',
  'english setter',
  'english springer spaniel',
  'english toy terrier (black&tan)',
  'entlebuch cattle dog',
  'estonian hound',
  'estrela mountain dog',
  'eurasian',
  'fawn brittany griffon',
  'field spaniel',
  'fila brasileiro',
  'finnish hound',
  'finnish lapponian dog',
  'finnish spitz',
  'flat coated retriever',
  'fox terrier (smooth)',
  'fox terrier (wire)',
  'french bulldog',
  'french pointing dog - gascogne type',
  'french pointing dog - pyrenean type',
  'french spaniel',
  'french tricolour hound',
  'french water dog',
  'french white & black hound',
  'french white and orange hound',
  'gascon saintongeois',
  'german hound',
  'german hunting terrier',
  'german pinscher',
  'german shepherd dog',
  'german short- haired pointing dog',
  'german spaniel',
  'german spitz',
  'german wire- haired pointing dog',
  'giant schnauzer',
  'golden retriever',
  'gordon setter',
  'grand basset griffon vendeen',
  'grand griffon vendeen',
  'great anglo-french tricolour hound',
  'great anglo-french white & orange hound',
  'great anglo-french white and black hound',
  'great dane',
  'great gascony blue',
  'great swiss mountain dog',
  'greenland dog',
  'greyhound',
  'griffon belge',
  'griffon bruxellois',
  'griffon nivernais',
  'halden hound',
  'hamiltonstövare',
  'hanoverian scent hound',
  'harrier',
  'havanese',
  'hellenic hound',
  'hokkaido',
  'hovawart',
  'hungarian greyhound',
  'hungarian hound - transylvanian scent hound',
  'hungarian short-haired pointer (vizsla)',
  'hungarian wire-haired pointer',
  'hygen hound',
  'ibizan podenco',
  'icelandic sheepdog',
  'irish glen of imaal terrier',
  'irish red and white setter',
  'irish red setter',
  'irish soft coated wheaten terrier',
  'irish terrier',
  'irish water spaniel',
  'irish wolfhound',
  'istrian short-haired hound',
  'istrian wire-haired hound',
  'italian cane corso',
  'italian pointing dog',
  'italian rough-haired segugio',
  'italian short-haired segugio',
  'italian sighthound',
  'italian spinone',
  'italian volpino',
  'jack russell terrier',
  'jämthund',
  'japanese chin',
  'japanese spitz',
  'japanese terrier',
  'kai',
  'kangal shepherd dog',
  'karelian bear dog',
  'karst shepherd dog',
  'kerry blue terrier',
  'king charles spaniel',
  'kintamani-bali dog',
  'kishu',
  'kleiner münsterländer',
  'komondor',
  'korea jindo dog',
  'kromfohrländer',
  'kuvasz',
  'labradoodle',
  'labrador retriever',
  'lakeland terrier',
  'lancashire heeler',
  'landseer (european continental type)',
  'lapponian herder',
  'large munsterlander',
  'leonberger',
  'lhasa apso',
  'little lion dog',
  'long-haired pyrenean sheepdog',
  'majorca mastiff',
  'majorca shepherd dog',
  'maltese',
  'manchester terrier',
  'maremma and the abruzzes sheepdog',
  'mastiff',
  'medium-sized anglo-french hound',
  'miniature american shepherd',
  'miniature bull terrier',
  'miniature pinscher',
  'miniature schnauzer',
  'montenegrin mountain hound',
  'mudi',
  'neapolitan mastiff',
  'nederlandse kooikerhondje',
  'newfoundland',
  'norfolk terrier',
  'norman artesien basset',
  'norrbottenspitz',
  'norwegian buhund',
  'norwegian elkhound black',
  'norwegian elkhound grey',
  'norwegian hound',
  'norwegian lundehund',
  'norwich terrier',
  'nova scotia duck tolling retriever',
  'old danish pointing dog',
  'old english sheepdog',
  'otterhound',
  'parson russell terrier',
  'pekingese',
  'peruvian hairless dog',
  'petit basset griffon vendeen',
  'petit brabançon',
  'pharaoh hound',
  'picardy sheepdog',
  'picardy spaniel',
  'poitevin',
  'polish greyhound',
  'polish hound',
  'polish hunting dog',
  'polish lowland sheepdog',
  'pont-audemer spaniel',
  'poodle',
  'porcelaine',
  'portuguese pointing dog',
  'portuguese sheepdog',
  'portuguese warren hound-portuguese podengo',
  'portuguese water dog',
  'posavatz hound',
  'prague ratter',
  'presa canario',
  'pudelpointer',
  'pug',
  'puli',
  'pumi',
  'pyrenean mastiff',
  'pyrenean mountain dog',
  'pyrenean sheepdog - smooth faced',
  'rafeiro of alentejo',
  'rhodesian ridgeback',
  'romagna water dog',
  'romanian bucovina shepherd',
  'romanian carpathian shepherd dog',
  'romanian mioritic shepherd dog',
  'rottweiler',
  'russian black terrier',
  'russian toy',
  'russian-european laika',
  'saarloos wolfhond',
  'saint germain pointer',
  'saint miguel cattle dog',
  'saluki',
  'samoyed',
  'schillerstövare',
  'schipperke',
  'schnauzer',
  'scottish terrier',
  'sealyham terrier',
  'segugio maremmano',
  'serbian hound',
  'serbian tricolour hound',
  'shar pei',
  'shetland sheepdog',
  'shiba',
  'shih tzu',
  'shikoku',
  'siberian husky',
  'skye terrier',
  'sloughi',
  'slovakian chuvach',
  'slovakian hound',
  'smålandsstövare',
  'small blue gascony',
  'small swiss hound',
  'south russian shepherd dog',
  'spanish greyhound',
  'spanish hound',
  'spanish mastiff',
  'spanish water dog',
  'st. bernard',
  'stabijhoun',
  'staffordshire bull terrier',
  'sussex spaniel',
  'swedish lapphund',
  'swedish vallhund',
  'swiss hound',
  'taiwan dog',
  'tatra shepherd dog',
  'thai bangkaew dog',
  'thai ridgeback dog',
  'tibetan mastiff',
  'tibetan spaniel',
  'tibetan terrier',
  'tosa',
  'transmontano mastiff',
  'tyrolean hound',
  'valencian terrier',
  'weimaraner',
  'welsh corgi (cardigan)',
  'welsh corgi (pembroke)',
  'welsh springer spaniel',
  'welsh terrier',
  'west highland white terrier',
  'west siberian laika',
  'westphalian dachsbracke',
  'wetterhoun',
  'whippet',
  'white swiss shepherd dog',
  'wire-haired pointing griffon korthals',
  'wirehaired slovakian pointer',
  'xoloitzcuintle',
  'yakutian laika',
  'yorkshire terrier',
  'yugoslavian shepherd dog - sharplanina',
  "cirneco dell'etna",
];
export const DOG_BREED_OPTIONS = [
  {
    id: 'duczi3d8r4f',
    label: 'Affenpinscher',
    value: 'affenpinscher',
  },
  {
    id: 'lbykticdla',
    label: 'Afghan Hound',
    value: 'afghan hound',
  },
  {
    id: 'rujihg2z2dm',
    label: 'Airedale Terrier',
    value: 'airedale terrier',
  },
  {
    id: 'l2xvpw2e09',
    label: 'Akita',
    value: 'akita',
  },
  {
    id: '5elfqjwstn5',
    label: 'Alaskan Husky',
    value: 'alaskan husky',
  },
  {
    id: '8g72d4cscbc',
    label: 'Alaskan Malamute',
    value: 'alaskan malamute',
  },
  {
    id: 'thy91kjz5jm',
    label: 'Alpine Dachsbracke',
    value: 'alpine dachsbracke',
  },
  {
    id: 'f7rnl8dv92m',
    label: 'American Akita',
    value: 'american akita',
  },
  {
    id: 'unvqgf8qpde',
    label: 'American Cocker Spaniel',
    value: 'american cocker spaniel',
  },
  {
    id: '32dcnrsjtaq',
    label: 'American Foxhound',
    value: 'american foxhound',
  },
  {
    id: 'cb90tx13w8e',
    label: 'American Staffordshire Terrier',
    value: 'american staffordshire terrier',
  },
  {
    id: 'wvc1ujibnfc',
    label: 'American Water Spaniel',
    value: 'american water spaniel',
  },
  {
    id: '07y4kfggdhu9',
    label: 'Appenzell Cattle Dog',
    value: 'appenzell cattle dog',
  },
  {
    id: 'lkt1ywiebn',
    label: 'Ariege Pointing Dog',
    value: 'ariege pointing dog',
  },
  {
    id: 'gpfnpxyljh6',
    label: 'Ariegeois',
    value: 'ariegeois',
  },
  {
    id: 'j8g3g7ruoa',
    label: 'Artois Hound',
    value: 'artois hound',
  },
  {
    id: 'rfbgn06dbqc',
    label: 'Atlas Mountain Dog (aidi)',
    value: 'atlas mountain dog (aidi)',
  },
  {
    id: 'pv62pntx5cr',
    label: 'Aussiedoodle',
    value: 'aussiedoodle',
  },
  {
    id: 'dn3rofpxldj',
    label: 'Australian Cattle Dog',
    value: 'australian cattle dog',
  },
  {
    id: 'p5elxomuwcj',
    label: 'Australian Kelpie',
    value: 'australian kelpie',
  },
  {
    id: 'b33uwq232ms',
    label: 'Australian Shepherd',
    value: 'australian shepherd',
  },
  {
    id: 'tnncuklhela',
    label: 'Australian Silky Terrier',
    value: 'australian silky terrier',
  },
  {
    id: 'jk34lo1863l',
    label: 'Australian Stumpy Tail Cattle Dog',
    value: 'australian stumpy tail cattle dog',
  },
  {
    id: 'edxrqg0px4b',
    label: 'Australian Terrier',
    value: 'australian terrier',
  },
  {
    id: '9a0krx5ly8s',
    label: 'Austrian  Pinscher',
    value: 'austrian  pinscher',
  },
  {
    id: 'ooce83kigje',
    label: 'Austrian Black And Tan Hound',
    value: 'austrian black and tan hound',
  },
  {
    id: 'bz2kutq2ham',
    label: 'Auvergne Pointer',
    value: 'auvergne pointer',
  },
  {
    id: '8tgizqp1nh6',
    label: 'Azawakh',
    value: 'azawakh',
  },
  {
    id: 'hxh94puq7rr',
    label: 'Basenji',
    value: 'basenji',
  },
  {
    id: '5o1ic3tajay',
    label: 'Basset Fauve De Bretagne',
    value: 'basset fauve de bretagne',
  },
  {
    id: 'xpegt363c1',
    label: 'Basset Hound',
    value: 'basset hound',
  },
  {
    id: 'uzh5y1q4nn',
    label: 'Bavarian Mountain Scent Hound',
    value: 'bavarian mountain scent hound',
  },
  {
    id: 'uv6g822r93a',
    label: 'Beagle Harrier',
    value: 'beagle harrier',
  },
  {
    id: 'w6xd0i6hii',
    label: 'Beagle',
    value: 'beagle',
  },
  {
    id: 'ki3ku4vcaw',
    label: 'Bearded Collie',
    value: 'bearded collie',
  },
  {
    id: '59sywltgee',
    label: 'Beauce Sheepdog',
    value: 'beauce sheepdog',
  },
  {
    id: 'ma7j1mp2uqk',
    label: 'Bedlington Terrier',
    value: 'bedlington terrier',
  },
  {
    id: 'zpxbxf2ob1j',
    label: 'Belgian Shepherd Dog',
    value: 'belgian shepherd dog',
  },
  {
    id: 'hrmhdpnaxnp',
    label: 'Bergamasco Shepherd Dog',
    value: 'bergamasco shepherd dog',
  },
  {
    id: 'aw4yrc8w8j4',
    label: 'Bernese Mountain Dog',
    value: 'bernese mountain dog',
  },
  {
    id: 'toggkhwirbc',
    label: 'Bichon Frise',
    value: 'bichon frise',
  },
  {
    id: '5ujcw4wa63f',
    label: 'Billy',
    value: 'billy',
  },
  {
    id: '7kuv3n6mf0j',
    label: 'Black And Tan Coonhound',
    value: 'black and tan coonhound',
  },
  {
    id: '32eblwpvb8u',
    label: 'Bloodhound',
    value: 'bloodhound',
  },
  {
    id: 'w14qbg4p3fe',
    label: 'Blue Gascony Basset',
    value: 'blue gascony basset',
  },
  {
    id: '767zlr3echw',
    label: 'Blue Gascony Griffon',
    value: 'blue gascony griffon',
  },
  {
    id: 'f0b54qd44o6',
    label: 'Blue Heeler',
    value: 'blue heeler',
  },
  {
    id: 'cpby3j2afhq',
    label: 'Blue Picardy Spaniel',
    value: 'blue picardy spaniel',
  },
  {
    id: 'cpe5v9bxuq',
    label: 'Bluetick Coonhound',
    value: 'bluetick coonhound',
  },
  {
    id: '5m50pcix2f6',
    label: 'Bohemian Shepherd Dog',
    value: 'bohemian shepherd dog',
  },
  {
    id: 'lv2bgd9t63p',
    label: 'Bohemian Wire-haired Pointing Griffon',
    value: 'bohemian wire-haired pointing griffon',
  },
  {
    id: '3nck4ir9bgp',
    label: 'Bolognese',
    value: 'bolognese',
  },
  {
    id: 'wh47t5ygvq',
    label: 'Border Collie',
    value: 'border collie',
  },
  {
    id: 'bfue5270bki',
    label: 'Border Terrier',
    value: 'border terrier',
  },
  {
    id: 'eiomzha2mws',
    label: 'Borzoi - Russian Hunting Sighthound',
    value: 'borzoi - russian hunting sighthound',
  },
  {
    id: 'kunj6fb8ex',
    label: 'Bosnian And Herzegovinian - Croatian Shepherd Dog',
    value: 'bosnian and herzegovinian - croatian shepherd dog',
  },
  {
    id: 'v49758ey5s',
    label: 'Bosnian Broken-haired Hound - Called Barak',
    value: 'bosnian broken-haired hound - called barak',
  },
  {
    id: 'svo7tlxnnw',
    label: 'Boston Terrier',
    value: 'boston terrier',
  },
  {
    id: 'wy2t4awufzn',
    label: 'Bourbonnais Pointing Dog',
    value: 'bourbonnais pointing dog',
  },
  {
    id: 'n5ehidvryqk',
    label: 'Bouvier Des Ardennes',
    value: 'bouvier des ardennes',
  },
  {
    id: 'd3sh8us7ccu',
    label: 'Bouvier Des Flandres',
    value: 'bouvier des flandres',
  },
  {
    id: '6yizrd7e90b',
    label: 'Boxer',
    value: 'boxer',
  },
  {
    id: 'ouvsg4ythte',
    label: 'Brazilian Terrier',
    value: 'brazilian terrier',
  },
  {
    id: 'ei0k0wefdnj',
    label: 'Brazilian Tracker',
    value: 'brazilian tracker',
  },
  {
    id: '6vdbro0306d',
    label: 'Briard',
    value: 'briard',
  },
  {
    id: '4qc22qdgk2e',
    label: 'Briquet Griffon Vendeen',
    value: 'briquet griffon vendeen',
  },
  {
    id: '4dodaii6rci',
    label: 'Brittany Spaniel',
    value: 'brittany spaniel',
  },
  {
    id: '3asa9jprei4',
    label: 'Broholmer',
    value: 'broholmer',
  },
  {
    id: 'j16eutheca8',
    label: 'Bull Terrier',
    value: 'bull terrier',
  },
  {
    id: 'cpe2c7j1dr4',
    label: 'Bulldog',
    value: 'bulldog',
  },
  {
    id: '411aydib0on',
    label: 'Bullmastiff',
    value: 'bullmastiff',
  },
  {
    id: 'gc809eefi59',
    label: 'Burgos Pointing Dog',
    value: 'burgos pointing dog',
  },
  {
    id: '7frqohemwmo',
    label: 'Cairn Terrier',
    value: 'cairn terrier',
  },
  {
    id: 'rulgmmq8zsn',
    label: 'Canaan Dog',
    value: 'canaan dog',
  },
  {
    id: '9i3kztv03j4',
    label: 'Canadian Eskimo Dog',
    value: 'canadian eskimo dog',
  },
  {
    id: 'opx3nj4cwqe',
    label: 'Canarian Warren Hound',
    value: 'canarian warren hound',
  },
  {
    id: '3m2eiinjek2',
    label: 'Castro Laboreiro Dog',
    value: 'castro laboreiro dog',
  },
  {
    id: 'gbwe3np7yq6',
    label: 'Catalan Sheepdog',
    value: 'catalan sheepdog',
  },
  {
    id: '7kvlqq8ojkv',
    label: 'Caucasian Shepherd Dog',
    value: 'caucasian shepherd dog',
  },
  {
    id: 'n51b92tt34s',
    label: 'Cavalier King Charles Spaniel',
    value: 'cavalier king charles spaniel',
  },
  {
    id: 'vgojc1f5ks',
    label: 'Central Asia Shepherd Dog',
    value: 'central asia shepherd dog',
  },
  {
    id: 'z1e545id31',
    label: 'Cesky Terrier',
    value: 'cesky terrier',
  },
  {
    id: 'g59l4alhfdj',
    label: 'Chesapeake Bay Retriever',
    value: 'chesapeake bay retriever',
  },
  {
    id: 'c8udyt60yei',
    label: 'Chihuahua',
    value: 'chihuahua',
  },
  {
    id: '7y7xss84vnu',
    label: 'Chinese Crested Dog',
    value: 'chinese crested dog',
  },
  {
    id: '127qc9tsdss',
    label: 'Chow Chow',
    value: 'chow chow',
  },
  {
    id: '322xjj52gvi',
    label: 'Cimarrón Uruguayo',
    value: 'cimarrón uruguayo',
  },
  {
    id: '9t4eu60up2',
    label: 'Clumber Spaniel',
    value: 'clumber spaniel',
  },
  {
    id: '18ilc90cov8',
    label: 'Coarse-haired Styrian Hound',
    value: 'coarse-haired styrian hound',
  },
  {
    id: '6fxkp4uvqf9',
    label: 'Collie Rough',
    value: 'collie rough',
  },
  {
    id: '1ru5y27fqio',
    label: 'Collie Smooth',
    value: 'collie smooth',
  },
  {
    id: 'tv7x9rn35p',
    label: 'Continental Bulldog',
    value: 'continental bulldog',
  },
  {
    id: '3be32v7z593',
    label: 'Continental Toy Spaniel',
    value: 'continental toy spaniel',
  },
  {
    id: '92p890r2x4',
    label: 'Coton De Tulear',
    value: 'coton de tulear',
  },
  {
    id: 'aoe83qo6bsv',
    label: 'Croatian Shepherd Dog',
    value: 'croatian shepherd dog',
  },
  {
    id: 'o5skq76u6l',
    label: 'Curly Coated Retriever',
    value: 'curly coated retriever',
  },
  {
    id: '6t62j6c5quj',
    label: 'Czechoslovakian Wolfdog',
    value: 'czechoslovakian wolfdog',
  },
  {
    id: 'mdfc48mvtec',
    label: 'Dachshund',
    value: 'dachshund',
  },
  {
    id: 'k7m1spix4il',
    label: 'Dalmatian',
    value: 'dalmatian',
  },
  {
    id: 'qzblcgj097',
    label: 'Dandie Dinmont Terrier',
    value: 'dandie dinmont terrier',
  },
  {
    id: '3lphfhxvx2m',
    label: 'Danish-swedish Farmdog',
    value: 'danish-swedish farmdog',
  },
  {
    id: '27y7lj41jey',
    label: 'Deerhound',
    value: 'deerhound',
  },
  {
    id: 'mh5fgs52arm',
    label: 'Deutsch Langhaar',
    value: 'deutsch langhaar',
  },
  {
    id: 'g44id1w5psc',
    label: 'Deutsch Stichelhaar',
    value: 'deutsch stichelhaar',
  },
  {
    id: 'l0u9l80x4fd',
    label: 'Dobermann',
    value: 'dobermann',
  },
  {
    id: '0y99nfp0kkkr',
    label: 'Dogo Argentino',
    value: 'dogo argentino',
  },
  {
    id: 'kh8mjk5ikfd',
    label: 'Dogue De Bordeaux',
    value: 'dogue de bordeaux',
  },
  {
    id: 'sf8ez8g6ja',
    label: 'Drentsche Partridge Dog',
    value: 'drentsche partridge dog',
  },
  {
    id: 's8itlfreofm',
    label: 'Drever',
    value: 'drever',
  },
  {
    id: 'h2x6jmhd459',
    label: 'Dutch Schapendoes',
    value: 'dutch schapendoes',
  },
  {
    id: 'kj2fxweli7',
    label: 'Dutch Shepherd Dog',
    value: 'dutch shepherd dog',
  },
  {
    id: '25jlbvcrkc6',
    label: 'Dutch Smoushond',
    value: 'dutch smoushond',
  },
  {
    id: 'g05zdvm8qre',
    label: 'East Siberian Laika',
    value: 'east siberian laika',
  },
  {
    id: 'n5fbt9659mi',
    label: 'English Cocker Spaniel',
    value: 'english cocker spaniel',
  },
  {
    id: 'nq8bco66du',
    label: 'English Foxhound',
    value: 'english foxhound',
  },
  {
    id: '3btt6ecuixi',
    label: 'English Pointer',
    value: 'english pointer',
  },
  {
    id: 'nrk67rc44j',
    label: 'English Setter',
    value: 'english setter',
  },
  {
    id: '7kd6u0szj88',
    label: 'English Springer Spaniel',
    value: 'english springer spaniel',
  },
  {
    id: 'jpidiw9kh5m',
    label: 'English Toy Terrier (black&tan)',
    value: 'english toy terrier (black&tan)',
  },
  {
    id: 'n5ebtomgzw',
    label: 'Entlebuch Cattle Dog',
    value: 'entlebuch cattle dog',
  },
  {
    id: 'mgpb8wifrhj',
    label: 'Estonian Hound',
    value: 'estonian hound',
  },
  {
    id: 'w90yogqouem',
    label: 'Estrela Mountain Dog',
    value: 'estrela mountain dog',
  },
  {
    id: 'lmut1wrorz',
    label: 'Eurasian',
    value: 'eurasian',
  },
  {
    id: '1dl1rr6uubm',
    label: 'Fawn Brittany Griffon',
    value: 'fawn brittany griffon',
  },
  {
    id: 'wstjc074ez',
    label: 'Field Spaniel',
    value: 'field spaniel',
  },
  {
    id: 'jhuh6x2aevk',
    label: 'Fila Brasileiro',
    value: 'fila brasileiro',
  },
  {
    id: 'yzfev2rde7a',
    label: 'Finnish Hound',
    value: 'finnish hound',
  },
  {
    id: 'sqpqf4z84fh',
    label: 'Finnish Lapponian Dog',
    value: 'finnish lapponian dog',
  },
  {
    id: 'aodorbjyugq',
    label: 'Finnish Spitz',
    value: 'finnish spitz',
  },
  {
    id: '5w0du6fv9fq',
    label: 'Flat Coated Retriever',
    value: 'flat coated retriever',
  },
  {
    id: 'xs8zjgyckg',
    label: 'Fox Terrier (smooth)',
    value: 'fox terrier (smooth)',
  },
  {
    id: 'p8ok4obl2be',
    label: 'Fox Terrier (wire)',
    value: 'fox terrier (wire)',
  },
  {
    id: '9xne6w7zypm',
    label: 'French Bulldog',
    value: 'french bulldog',
  },
  {
    id: '3eus5zmpcqa',
    label: 'French Pointing Dog - Gascogne Type',
    value: 'french pointing dog - gascogne type',
  },
  {
    id: 'cdv9y02a89k',
    label: 'French Pointing Dog - Pyrenean Type',
    value: 'french pointing dog - pyrenean type',
  },
  {
    id: '13glqju8zvvd',
    label: 'French Spaniel',
    value: 'french spaniel',
  },
  {
    id: 'hni6k953cck',
    label: 'French Tricolour Hound',
    value: 'french tricolour hound',
  },
  {
    id: 'jiqqen5rghd',
    label: 'French Water Dog',
    value: 'french water dog',
  },
  {
    id: 'dxz62ilrvkr',
    label: 'French White & Black Hound',
    value: 'french white & black hound',
  },
  {
    id: 'm4kth02eauc',
    label: 'French White And Orange Hound',
    value: 'french white and orange hound',
  },
  {
    id: 'xo09n06vgjg',
    label: 'Gascon Saintongeois',
    value: 'gascon saintongeois',
  },
  {
    id: 'bcobssqu7yl',
    label: 'German Hound',
    value: 'german hound',
  },
  {
    id: 'oin878uo1e',
    label: 'German Hunting Terrier',
    value: 'german hunting terrier',
  },
  {
    id: 'lvzhwfab6mn',
    label: 'German Pinscher',
    value: 'german pinscher',
  },
  {
    id: 'v52lvv3bwsh',
    label: 'German Shepherd Dog',
    value: 'german shepherd dog',
  },
  {
    id: 'r03iujilzh',
    label: 'German Short- Haired Pointing Dog',
    value: 'german short- haired pointing dog',
  },
  {
    id: 'oqqdy648ne',
    label: 'German Spaniel',
    value: 'german spaniel',
  },
  {
    id: 'gwvhmlup0oi',
    label: 'German Spitz',
    value: 'german spitz',
  },
  {
    id: 'gnwyn0z851q',
    label: 'German Wire- Haired Pointing Dog',
    value: 'german wire- haired pointing dog',
  },
  {
    id: 'ybd0yjdkpji',
    label: 'Giant Schnauzer',
    value: 'giant schnauzer',
  },
  {
    id: '19e59ddocxj',
    label: 'Golden Retriever',
    value: 'golden retriever',
  },
  {
    id: 'qmyje0qhds',
    label: 'Gordon Setter',
    value: 'gordon setter',
  },
  {
    id: 't8ad966cvc7',
    label: 'Grand Basset Griffon Vendeen',
    value: 'grand basset griffon vendeen',
  },
  {
    id: '4tkp6kuxvxs',
    label: 'Grand Griffon Vendeen',
    value: 'grand griffon vendeen',
  },
  {
    id: '0bzg3sx10xkr',
    label: 'Great Anglo-french Tricolour Hound',
    value: 'great anglo-french tricolour hound',
  },
  {
    id: 'u9gyaxivfue',
    label: 'Great Anglo-french White & Orange Hound',
    value: 'great anglo-french white & orange hound',
  },
  {
    id: 'cv04p2rhq8r',
    label: 'Great Anglo-french White And Black Hound',
    value: 'great anglo-french white and black hound',
  },
  {
    id: '08eqei6omruv',
    label: 'Great Dane',
    value: 'great dane',
  },
  {
    id: '7p3a477r6um',
    label: 'Great Gascony Blue',
    value: 'great gascony blue',
  },
  {
    id: 'gf4miswbp56',
    label: 'Great Swiss Mountain Dog',
    value: 'great swiss mountain dog',
  },
  {
    id: 'yyjfsfc6exh',
    label: 'Greenland Dog',
    value: 'greenland dog',
  },
  {
    id: 'utzbyjgkh0h',
    label: 'Greyhound',
    value: 'greyhound',
  },
  {
    id: '9g9e8td5wa',
    label: 'Griffon Belge',
    value: 'griffon belge',
  },
  {
    id: 'e0ts47p9gjl',
    label: 'Griffon Bruxellois',
    value: 'griffon bruxellois',
  },
  {
    id: 'raj0yt2j8e',
    label: 'Griffon Nivernais',
    value: 'griffon nivernais',
  },
  {
    id: 'qrvtk7hg4n',
    label: 'Halden Hound',
    value: 'halden hound',
  },
  {
    id: 'g0cg2kshgbr',
    label: 'Hamiltonstövare',
    value: 'hamiltonstövare',
  },
  {
    id: 'yb3zudoov5q',
    label: 'Hanoverian Scent Hound',
    value: 'hanoverian scent hound',
  },
  {
    id: 'fv477gljf2h',
    label: 'Harrier',
    value: 'harrier',
  },
  {
    id: '24cjpknzxml',
    label: 'Havanese',
    value: 'havanese',
  },
  {
    id: 'qgtplvdi1i',
    label: 'Hellenic Hound',
    value: 'hellenic hound',
  },
  {
    id: '9di3ll77pp4',
    label: 'Hokkaido',
    value: 'hokkaido',
  },
  {
    id: 'f3rjjy0mtl7',
    label: 'Hovawart',
    value: 'hovawart',
  },
  {
    id: 'tn96168b1yf',
    label: 'Hungarian Greyhound',
    value: 'hungarian greyhound',
  },
  {
    id: '6nximqx27u',
    label: 'Hungarian Hound - Transylvanian Scent Hound',
    value: 'hungarian hound - transylvanian scent hound',
  },
  {
    id: 'ktbszvguj7o',
    label: 'Hungarian Short-haired Pointer (vizsla)',
    value: 'hungarian short-haired pointer (vizsla)',
  },
  {
    id: 'fiszl5xk3ct',
    label: 'Hungarian Wire-haired Pointer',
    value: 'hungarian wire-haired pointer',
  },
  {
    id: 'lr3vd6jnx8f',
    label: 'Hygen Hound',
    value: 'hygen hound',
  },
  {
    id: 'v3khqlnzjs',
    label: 'Ibizan Podenco',
    value: 'ibizan podenco',
  },
  {
    id: 'i0moode3rf',
    label: 'Icelandic Sheepdog',
    value: 'icelandic sheepdog',
  },
  {
    id: 'z74a44ev2zn',
    label: 'Irish Glen Of Imaal Terrier',
    value: 'irish glen of imaal terrier',
  },
  {
    id: 'ww0xftmwkai',
    label: 'Irish Red And White Setter',
    value: 'irish red and white setter',
  },
  {
    id: 'bf64gygzq9f',
    label: 'Irish Red Setter',
    value: 'irish red setter',
  },
  {
    id: 'uxf16wbv7jn',
    label: 'Irish Soft Coated Wheaten Terrier',
    value: 'irish soft coated wheaten terrier',
  },
  {
    id: 's0cu05h011c',
    label: 'Irish Terrier',
    value: 'irish terrier',
  },
  {
    id: '96p89n6qre',
    label: 'Irish Water Spaniel',
    value: 'irish water spaniel',
  },
  {
    id: 'swzzinb5wnr',
    label: 'Irish Wolfhound',
    value: 'irish wolfhound',
  },
  {
    id: '9keylkdqyd8',
    label: 'Istrian Short-haired Hound',
    value: 'istrian short-haired hound',
  },
  {
    id: 'v1l82uk8oo9',
    label: 'Istrian Wire-haired Hound',
    value: 'istrian wire-haired hound',
  },
  {
    id: 's4y2wzah1qi',
    label: 'Italian Cane Corso',
    value: 'italian cane corso',
  },
  {
    id: 'dpxoah6gh0j',
    label: 'Italian Pointing Dog',
    value: 'italian pointing dog',
  },
  {
    id: '59nuqtyg5hk',
    label: 'Italian Rough-haired Segugio',
    value: 'italian rough-haired segugio',
  },
  {
    id: 'butw4fgr7z',
    label: 'Italian Short-haired Segugio',
    value: 'italian short-haired segugio',
  },
  {
    id: '8w6bvcw2bgw',
    label: 'Italian Sighthound',
    value: 'italian sighthound',
  },
  {
    id: '0himoqhapcb7',
    label: 'Italian Spinone',
    value: 'italian spinone',
  },
  {
    id: 'frzrb7xhk1r',
    label: 'Italian Volpino',
    value: 'italian volpino',
  },
  {
    id: 'caki57la6ce',
    label: 'Jack Russell Terrier',
    value: 'jack russell terrier',
  },
  {
    id: '09q7um15fye2',
    label: 'Jämthund',
    value: 'jämthund',
  },
  {
    id: '2zrp6kn85gq',
    label: 'Japanese Chin',
    value: 'japanese chin',
  },
  {
    id: '6xmlx1q8ki9',
    label: 'Japanese Spitz',
    value: 'japanese spitz',
  },
  {
    id: '0463x95pcwnn',
    label: 'Japanese Terrier',
    value: 'japanese terrier',
  },
  {
    id: 'aj11j7o1nx7',
    label: 'Kai',
    value: 'kai',
  },
  {
    id: 'me1jkyqt7t',
    label: 'Kangal Shepherd Dog',
    value: 'kangal shepherd dog',
  },
  {
    id: 'mo7rkrr2c8h',
    label: 'Karelian Bear Dog',
    value: 'karelian bear dog',
  },
  {
    id: '40mxnapqvpe',
    label: 'Karst Shepherd Dog',
    value: 'karst shepherd dog',
  },
  {
    id: '1ctaoydx5csh',
    label: 'Kerry Blue Terrier',
    value: 'kerry blue terrier',
  },
  {
    id: 'gng7iecaup',
    label: 'King Charles Spaniel',
    value: 'king charles spaniel',
  },
  {
    id: 'rvl6bgz09wi',
    label: 'Kintamani-bali Dog',
    value: 'kintamani-bali dog',
  },
  {
    id: '4f7jghc86p5',
    label: 'Kishu',
    value: 'kishu',
  },
  {
    id: 'y2t7aqr6xwa',
    label: 'Kleiner Münsterländer',
    value: 'kleiner münsterländer',
  },
  {
    id: 'k3ml0vwsofi',
    label: 'Komondor',
    value: 'komondor',
  },
  {
    id: 'sluk3pbxsxj',
    label: 'Korea Jindo Dog',
    value: 'korea jindo dog',
  },
  {
    id: 'mq3zmtmr20e',
    label: 'Kromfohrländer',
    value: 'kromfohrländer',
  },
  {
    id: 't5c0yy91to',
    label: 'Kuvasz',
    value: 'kuvasz',
  },
  {
    id: 'qfal3lqggwk',
    label: 'Labradoodle',
    value: 'labradoodle',
  },
  {
    id: 'd20anm5kj3f',
    label: 'Labrador Retriever',
    value: 'labrador retriever',
  },
  {
    id: 'jxvt18et63a',
    label: 'Lakeland Terrier',
    value: 'lakeland terrier',
  },
  {
    id: 'd1009f3kpu',
    label: 'Lancashire Heeler',
    value: 'lancashire heeler',
  },
  {
    id: 'pi8paqfu8bq',
    label: 'Landseer (european Continental Type)',
    value: 'landseer (european continental type)',
  },
  {
    id: 'd2v2exuubjl',
    label: 'Lapponian Herder',
    value: 'lapponian herder',
  },
  {
    id: 'z55fx5qwxls',
    label: 'Large Munsterlander',
    value: 'large munsterlander',
  },
  {
    id: 'dfxmdjvhom',
    label: 'Leonberger',
    value: 'leonberger',
  },
  {
    id: 'km7jy7vbmo',
    label: 'Lhasa Apso',
    value: 'lhasa apso',
  },
  {
    id: '7toexkzbppb',
    label: 'Little Lion Dog',
    value: 'little lion dog',
  },
  {
    id: 'cpskrpibiso',
    label: 'Long-haired Pyrenean Sheepdog',
    value: 'long-haired pyrenean sheepdog',
  },
  {
    id: 'zcc8xlto6l',
    label: 'Majorca Mastiff',
    value: 'majorca mastiff',
  },
  {
    id: 'gnwo2j4w6z',
    label: 'Majorca Shepherd Dog',
    value: 'majorca shepherd dog',
  },
  {
    id: 'j688xjmcmon',
    label: 'Maltese',
    value: 'maltese',
  },
  {
    id: 'w57urbwdv7m',
    label: 'Manchester Terrier',
    value: 'manchester terrier',
  },
  {
    id: 'b1gwti7snpg',
    label: 'Maremma And The Abruzzes Sheepdog',
    value: 'maremma and the abruzzes sheepdog',
  },
  {
    id: '53ua8ja1338',
    label: 'Mastiff',
    value: 'mastiff',
  },
  {
    id: '7zscqbwigf4',
    label: 'Medium-sized Anglo-french Hound',
    value: 'medium-sized anglo-french hound',
  },
  {
    id: 'rohtdgl41j',
    label: 'Miniature American Shepherd',
    value: 'miniature american shepherd',
  },
  {
    id: '5z59nicf42k',
    label: 'Miniature Bull Terrier',
    value: 'miniature bull terrier',
  },
  {
    id: 'oee94giwx8a',
    label: 'Miniature Pinscher',
    value: 'miniature pinscher',
  },
  {
    id: '8w6rcd53h07',
    label: 'Miniature Schnauzer',
    value: 'miniature schnauzer',
  },
  {
    id: '84q40ofhbil',
    label: 'Montenegrin Mountain Hound',
    value: 'montenegrin mountain hound',
  },
  {
    id: 'r0ycy7u6sca',
    label: 'Mudi',
    value: 'mudi',
  },
  {
    id: 'w2stttrsvy',
    label: 'Neapolitan Mastiff',
    value: 'neapolitan mastiff',
  },
  {
    id: 'b3rwn9iksso',
    label: 'Nederlandse Kooikerhondje',
    value: 'nederlandse kooikerhondje',
  },
  {
    id: '26nzbfsu2bg',
    label: 'Newfoundland',
    value: 'newfoundland',
  },
  {
    id: 't9u5c5m4oiq',
    label: 'Norfolk Terrier',
    value: 'norfolk terrier',
  },
  {
    id: 'cr2yk2h0ayg',
    label: 'Norman Artesien Basset',
    value: 'norman artesien basset',
  },
  {
    id: 's7lo6oxueoc',
    label: 'Norrbottenspitz',
    value: 'norrbottenspitz',
  },
  {
    id: '2n06z0rmeae',
    label: 'Norwegian Buhund',
    value: 'norwegian buhund',
  },
  {
    id: 'lbovtest6ga',
    label: 'Norwegian Elkhound Black',
    value: 'norwegian elkhound black',
  },
  {
    id: 'p4a4uvmccnq',
    label: 'Norwegian Elkhound Grey',
    value: 'norwegian elkhound grey',
  },
  {
    id: 'xiu0f6rota',
    label: 'Norwegian Hound',
    value: 'norwegian hound',
  },
  {
    id: 'y81dn4segl7',
    label: 'Norwegian Lundehund',
    value: 'norwegian lundehund',
  },
  {
    id: 'j655pvkdsmf',
    label: 'Norwich Terrier',
    value: 'norwich terrier',
  },
  {
    id: 'sjknz19nca8',
    label: 'Nova Scotia Duck Tolling Retriever',
    value: 'nova scotia duck tolling retriever',
  },
  {
    id: 'zkkw7jgwn1b',
    label: 'Old Danish Pointing Dog',
    value: 'old danish pointing dog',
  },
  {
    id: '20ejog1ja12',
    label: 'Old English Sheepdog',
    value: 'old english sheepdog',
  },
  {
    id: '456sgkvxjz5',
    label: 'Otterhound',
    value: 'otterhound',
  },
  {
    id: '9wyjn7uzct',
    label: 'Parson Russell Terrier',
    value: 'parson russell terrier',
  },
  {
    id: 'pl37d8ut7bp',
    label: 'Pekingese',
    value: 'pekingese',
  },
  {
    id: 'iqhxmiowifn',
    label: 'Peruvian Hairless Dog',
    value: 'peruvian hairless dog',
  },
  {
    id: 'zsp4or95fd',
    label: 'Petit Basset Griffon Vendeen',
    value: 'petit basset griffon vendeen',
  },
  {
    id: 'zjfpaknk4u',
    label: 'Petit Brabançon',
    value: 'petit brabançon',
  },
  {
    id: 'xfzi36bkrw',
    label: 'Pharaoh Hound',
    value: 'pharaoh hound',
  },
  {
    id: 'ugd9y8qa10p',
    label: 'Picardy Sheepdog',
    value: 'picardy sheepdog',
  },
  {
    id: 'xr1t8729kx8',
    label: 'Picardy Spaniel',
    value: 'picardy spaniel',
  },
  {
    id: 'hssbbmnfz1l',
    label: 'Poitevin',
    value: 'poitevin',
  },
  {
    id: 'xq8wz59zloh',
    label: 'Polish Greyhound',
    value: 'polish greyhound',
  },
  {
    id: 'ldio8g14nqe',
    label: 'Polish Hound',
    value: 'polish hound',
  },
  {
    id: 'mi6n1diqyqg',
    label: 'Polish Hunting Dog',
    value: 'polish hunting dog',
  },
  {
    id: 'v20pmbku85d',
    label: 'Polish Lowland Sheepdog',
    value: 'polish lowland sheepdog',
  },
  {
    id: '9nufarr5hwc',
    label: 'Pont-audemer Spaniel',
    value: 'pont-audemer spaniel',
  },
  {
    id: 'ppjh4jbvln',
    label: 'Poodle',
    value: 'poodle',
  },
  {
    id: 'h8vag5u0rud',
    label: 'Porcelaine',
    value: 'porcelaine',
  },
  {
    id: 'hw0xqblq5r7',
    label: 'Portuguese Pointing Dog',
    value: 'portuguese pointing dog',
  },
  {
    id: 'v1qieac88zj',
    label: 'Portuguese Sheepdog',
    value: 'portuguese sheepdog',
  },
  {
    id: 'gejszpu4y5',
    label: 'Portuguese Warren Hound-portuguese Podengo',
    value: 'portuguese warren hound-portuguese podengo',
  },
  {
    id: 'ol54uczwdmp',
    label: 'Portuguese Water Dog',
    value: 'portuguese water dog',
  },
  {
    id: '8kb5ug2c0l5',
    label: 'Posavatz Hound',
    value: 'posavatz hound',
  },
  {
    id: 'uxlvg6jqf3a',
    label: 'Prague Ratter',
    value: 'prague ratter',
  },
  {
    id: '64bfsypka9u',
    label: 'Presa Canario',
    value: 'presa canario',
  },
  {
    id: '7xl27cgya0o',
    label: 'Pudelpointer',
    value: 'pudelpointer',
  },
  {
    id: 'v1zpyny5sh',
    label: 'Pug',
    value: 'pug',
  },
  {
    id: '874wdsd3k13',
    label: 'Puli',
    value: 'puli',
  },
  {
    id: '4betrhvkkpq',
    label: 'Pumi',
    value: 'pumi',
  },
  {
    id: 'of57s0qfdj',
    label: 'Pyrenean Mastiff',
    value: 'pyrenean mastiff',
  },
  {
    id: 'etr0ropkupt',
    label: 'Pyrenean Mountain Dog',
    value: 'pyrenean mountain dog',
  },
  {
    id: 'zh3bltnruj',
    label: 'Pyrenean Sheepdog - Smooth Faced',
    value: 'pyrenean sheepdog - smooth faced',
  },
  {
    id: 'is1ytkduct',
    label: 'Rafeiro Of Alentejo',
    value: 'rafeiro of alentejo',
  },
  {
    id: 'tp0hqojo6x',
    label: 'Rhodesian Ridgeback',
    value: 'rhodesian ridgeback',
  },
  {
    id: 'bfr8vs8xywv',
    label: 'Romagna Water Dog',
    value: 'romagna water dog',
  },
  {
    id: 'pw6zgk9n3b',
    label: 'Romanian Bucovina Shepherd',
    value: 'romanian bucovina shepherd',
  },
  {
    id: 'tofnlv1rw2s',
    label: 'Romanian Carpathian Shepherd Dog',
    value: 'romanian carpathian shepherd dog',
  },
  {
    id: 'q0mo9gctuib',
    label: 'Romanian Mioritic Shepherd Dog',
    value: 'romanian mioritic shepherd dog',
  },
  {
    id: '0d6iqymocdmh',
    label: 'Rottweiler',
    value: 'rottweiler',
  },
  {
    id: 'hgftkaryay7',
    label: 'Russian Black Terrier',
    value: 'russian black terrier',
  },
  {
    id: 'jnshe1s1ej',
    label: 'Russian Toy',
    value: 'russian toy',
  },
  {
    id: 'b07jw9futa9',
    label: 'Russian-european Laika',
    value: 'russian-european laika',
  },
  {
    id: '0hwoxj8yz36',
    label: 'Saarloos Wolfhond',
    value: 'saarloos wolfhond',
  },
  {
    id: 'myd1pcidmuc',
    label: 'Saint Germain Pointer',
    value: 'saint germain pointer',
  },
  {
    id: '4lf93rke8v9',
    label: 'Saint Miguel Cattle Dog',
    value: 'saint miguel cattle dog',
  },
  {
    id: 'owpxefq8fj',
    label: 'Saluki',
    value: 'saluki',
  },
  {
    id: 'q8czbk2pqc9',
    label: 'Samoyed',
    value: 'samoyed',
  },
  {
    id: '6lk7qsgcq2l',
    label: 'Schillerstövare',
    value: 'schillerstövare',
  },
  {
    id: 'rbxfi4wy60t',
    label: 'Schipperke',
    value: 'schipperke',
  },
  {
    id: '72nt7x6q80m',
    label: 'Schnauzer',
    value: 'schnauzer',
  },
  {
    id: 'rzw0awubp69',
    label: 'Scottish Terrier',
    value: 'scottish terrier',
  },
  {
    id: 'pgyismpuzb',
    label: 'Sealyham Terrier',
    value: 'sealyham terrier',
  },
  {
    id: 'vhyk2s2jxza',
    label: 'Segugio Maremmano',
    value: 'segugio maremmano',
  },
  {
    id: 'd03anyep4te',
    label: 'Serbian Hound',
    value: 'serbian hound',
  },
  {
    id: 's44jb1kec4a',
    label: 'Serbian Tricolour Hound',
    value: 'serbian tricolour hound',
  },
  {
    id: '053ide24xsrh',
    label: 'Shar Pei',
    value: 'shar pei',
  },
  {
    id: 'o8k64nuqjd',
    label: 'Shetland Sheepdog',
    value: 'shetland sheepdog',
  },
  {
    id: 'dt5va22234n',
    label: 'Shiba',
    value: 'shiba',
  },
  {
    id: 's4jhnyjw9bp',
    label: 'Shih Tzu',
    value: 'shih tzu',
  },
  {
    id: 'd1sq3ygbv2e',
    label: 'Shikoku',
    value: 'shikoku',
  },
  {
    id: 'xssbhn97qkq',
    label: 'Siberian Husky',
    value: 'siberian husky',
  },
  {
    id: 'zgp8uq5mavj',
    label: 'Skye Terrier',
    value: 'skye terrier',
  },
  {
    id: 'jlcjxmc6ko',
    label: 'Sloughi',
    value: 'sloughi',
  },
  {
    id: 'scid9ab3q7',
    label: 'Slovakian Chuvach',
    value: 'slovakian chuvach',
  },
  {
    id: '4e2zjpy9v7t',
    label: 'Slovakian Hound',
    value: 'slovakian hound',
  },
  {
    id: 'scvua2zdwgp',
    label: 'Smålandsstövare',
    value: 'smålandsstövare',
  },
  {
    id: 'eg7tr5m2gwt',
    label: 'Small Blue Gascony',
    value: 'small blue gascony',
  },
  {
    id: 'nh9kctujbm',
    label: 'Small Swiss Hound',
    value: 'small swiss hound',
  },
  {
    id: 'aydpzlo7pyh',
    label: 'South Russian Shepherd Dog',
    value: 'south russian shepherd dog',
  },
  {
    id: 'xtn5oo5ewt',
    label: 'Spanish Greyhound',
    value: 'spanish greyhound',
  },
  {
    id: 'jod0oapqdj',
    label: 'Spanish Hound',
    value: 'spanish hound',
  },
  {
    id: 'f0evy9h58t5',
    label: 'Spanish Mastiff',
    value: 'spanish mastiff',
  },
  {
    id: 'gd5cw4813kr',
    label: 'Spanish Water Dog',
    value: 'spanish water dog',
  },
  {
    id: '2190vvraabx',
    label: 'St. Bernard',
    value: 'st. bernard',
  },
  {
    id: '1npcrdgdi68i',
    label: 'Stabijhoun',
    value: 'stabijhoun',
  },
  {
    id: 'jbzwvarjymm',
    label: 'Staffordshire Bull Terrier',
    value: 'staffordshire bull terrier',
  },
  {
    id: '1g8m2e85dk1',
    label: 'Sussex Spaniel',
    value: 'sussex spaniel',
  },
  {
    id: 'vrj0ekfwpnj',
    label: 'Swedish Lapphund',
    value: 'swedish lapphund',
  },
  {
    id: '46z3odf0if2',
    label: 'Swedish Vallhund',
    value: 'swedish vallhund',
  },
  {
    id: '07wr5rpvhpdr',
    label: 'Swiss Hound',
    value: 'swiss hound',
  },
  {
    id: '341mzkuayqn',
    label: 'Taiwan Dog',
    value: 'taiwan dog',
  },
  {
    id: 'cf87l6n6ybt',
    label: 'Tatra Shepherd Dog',
    value: 'tatra shepherd dog',
  },
  {
    id: '85mn3hdahj8',
    label: 'Thai Bangkaew Dog',
    value: 'thai bangkaew dog',
  },
  {
    id: 'c3l7r5f6ow6',
    label: 'Thai Ridgeback Dog',
    value: 'thai ridgeback dog',
  },
  {
    id: 'fo6x3jmo5e8',
    label: 'Tibetan Mastiff',
    value: 'tibetan mastiff',
  },
  {
    id: 'yjmkszj7ohd',
    label: 'Tibetan Spaniel',
    value: 'tibetan spaniel',
  },
  {
    id: 'v6gn6vdgo4o',
    label: 'Tibetan Terrier',
    value: 'tibetan terrier',
  },
  {
    id: 'ssu2r0rkva',
    label: 'Tosa',
    value: 'tosa',
  },
  {
    id: '7at9dytopht',
    label: 'Transmontano Mastiff',
    value: 'transmontano mastiff',
  },
  {
    id: 'gz51fcwvl9q',
    label: 'Tyrolean Hound',
    value: 'tyrolean hound',
  },
  {
    id: 'yndnoe9pbpl',
    label: 'Valencian Terrier',
    value: 'valencian terrier',
  },
  {
    id: '6jb1ohkbwn3',
    label: 'Weimaraner',
    value: 'weimaraner',
  },
  {
    id: 'a7ksm0l9do4',
    label: 'Welsh Corgi (cardigan)',
    value: 'welsh corgi (cardigan)',
  },
  {
    id: '2rtxm977ovn',
    label: 'Welsh Corgi (pembroke)',
    value: 'welsh corgi (pembroke)',
  },
  {
    id: 'lcuxf8o57z',
    label: 'Welsh Springer Spaniel',
    value: 'welsh springer spaniel',
  },
  {
    id: 'ync0co82w5',
    label: 'Welsh Terrier',
    value: 'welsh terrier',
  },
  {
    id: 'w2fjdbfdrtr',
    label: 'West Highland White Terrier',
    value: 'west highland white terrier',
  },
  {
    id: 'gtyxudqtkml',
    label: 'West Siberian Laika',
    value: 'west siberian laika',
  },
  {
    id: 'cvmwo04gqim',
    label: 'Westphalian Dachsbracke',
    value: 'westphalian dachsbracke',
  },
  {
    id: 'd4rqcm0199k',
    label: 'Wetterhoun',
    value: 'wetterhoun',
  },
  {
    id: 'r7ztfx39kz',
    label: 'Whippet',
    value: 'whippet',
  },
  {
    id: 'gel3now4gw',
    label: 'White Swiss Shepherd Dog',
    value: 'white swiss shepherd dog',
  },
  {
    id: 'yh8mlshqph',
    label: 'Wire-haired Pointing Griffon Korthals',
    value: 'wire-haired pointing griffon korthals',
  },
  {
    id: 'xvg1sc6q4w',
    label: 'Wirehaired Slovakian Pointer',
    value: 'wirehaired slovakian pointer',
  },
  {
    id: 'wfxb60shvx',
    label: 'Xoloitzcuintle',
    value: 'xoloitzcuintle',
  },
  {
    id: 'xn1bsv6n2a',
    label: 'Yakutian Laika',
    value: 'yakutian laika',
  },
  {
    id: 'y1nhd829c49',
    label: 'Yorkshire Terrier',
    value: 'yorkshire terrier',
  },
  {
    id: 'c86nhmvuptj',
    label: 'Yugoslavian Shepherd Dog - Sharplanina',
    value: 'yugoslavian shepherd dog - sharplanina',
  },
  {
    id: '3c2fn9q4lm2',
    label: "Cirneco Dell'etna",
    value: "cirneco dell'etna",
  },
];

export const DOG_AGES = [
  'Puppy (0–9 months)',
  'Young (9 months – 2 years)',
  'Adult (2–8 years)',
  'Senior (8+ years)',
];
export const DOG_AGE_OPTIONS = [
  {
    id: '5olpqsjlvf6',
    label: 'Puppy (0–9 Months)',
    value: 'puppy (0–9 months)',
  },
  {
    id: 'wtz34frhcgb',
    label: 'Young (9 Months – 2 Years)',
    value: 'young (9 months – 2 years)',
  },
  {
    id: 'rzoxz7ljf9',
    label: 'Adult (2–8 Years)',
    value: 'adult (2–8 years)',
  },
  {
    id: '5zs17oz2198',
    label: 'Senior (8+ Years)',
    value: 'senior (8+ years)',
  },
];

export const DOG_SIZES = [
  'Small (0–15 lbs)',
  'Medium (16–40 lbs)',
  'Large (41–100 lbs)',
  'Extra large (101+ lbs)',
];
export const DOG_SIZE_OPTIONS = [
  {
    id: 'uh457bd6zc',
    label: 'Small (0–15 Lbs)',
    value: 'small (0–15 lbs)',
  },
  {
    id: '50d8pk8kxpj',
    label: 'Medium (16–40 Lbs)',
    value: 'medium (16–40 lbs)',
  },
  {
    id: 'wyin6hsd8po',
    label: 'Large (41–100 Lbs)',
    value: 'large (41–100 lbs)',
  },
  {
    id: 'v89lla6mvz',
    label: 'Extra Large (101+ Lbs)',
    value: 'extra large (101+ lbs)',
  },
];
